version = "1.1.1"

[class]
taskwarrior-tui = ""
pavucontrol = ""
dmenu-browser = ""
"org.telegram.desktop" = ""
zoom = ""
spotify = ""
snappergui = ""
libreoffice-impress = ""
whatsapp-nativefier-d52542 = ""
streamlink-twitch-gui = ""
udiskie = ""
wayvnc = "󰀄"
burp-startburp = ""
org-telegram-desktop = ""
Signal = ""
libreoffice-writer = ""
cssh = ""
libreoffice-calc = ""
firefox = ""
songrec = ""
darktable = ""
org-qutebrowser-qutebrowser = ""
libreoffice-startcenter = ""
vimiv = ""
"(?i)kitty" = ""
vlc = ""
discord = ""
scli = ""
plexamp = ""
chromium = ""
krita = ""
qalculate-gtk = ""
rapid-photo-downloader = ""
jetbrains-studio = ""
fontforge = ""
DEFAULT = ""
nm-connection-editor = ""
personal = ""
"Gimp-2.10" = ""
xplr = ""
molotov = ""
work = ""
telegramdesktop = ""
Code = ""
mpv = ""
duolingo = ""
".*transmission.*" = ""
swappy = ""
gcr-prompter = ""
dmenu-clipboard = ""
shopping = ""
steam = ""
sandboxed-tor-browser = ""
code-oss = ""
calibre-gui = ""
obsidian = ""
paperwork = ""
dmenu-emoji = ""
FFPWA-01H2RKDZVRMHNK0MK61SQY4BYV = ""
"(?i)waydroid.*" = "droid"
gsimplecalc = ""
remote-viewer = ""
nemo = ""
kak = ""
kicad = ""
bleachbit = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
org-pwmt-zathura = ""
"(?i)alacritty" = ""
element = ""
slack = ""
wireshark-gtk = ""
qutepreview = ""
org-ksnip-ksnip = ""
vncviewer = ""
wire = "󰁀"
neomutt = ""
dmenu-pass = ""
virt-manager = ""
sun-awt-x11-xframepeer = ""
whatsapp-desktop = ""
wlfreerdp = "󰀄"
"dmenu-pass generator" = ""

[class_active]
"(?i)firefox" = "<span foreground='orange'> </span>"

[initial_class]

[initial_class_active]

[workspaces_name]
5 = "five"
9 = "nine"
7 = "seven"
1 = "one"
6 = "six"
4 = "four"
3 = "three"
0 = "zero"
10 = "ten"
2 = "two"
8 = "eight"

[title_in_class]

[title_in_class_active]
[title_in_initial_class.kitty]
pacu = ""
aurs = ""

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]

[format]
dedup = true
dedup_inactive_fullscreen = true
delim = " "
workspace = "{id}:<span color='#ebdbb2'>{delim}{clients}</span>"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "<span color='#b8bb26'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
