version = "1.1.0"

[class]
whatsapp-nativefier-d52542 = ""
swappy = ""
personal = ""
org-ksnip-ksnip = ""
virt-manager = ""
DEFAULT = ""
dmenu-browser = ""
calibre-gui = ""
sandboxed-tor-browser = ""
org-pwmt-zathura = ""
libreoffice-startcenter = ""
zoom = ""
vncviewer = ""
code-oss = ""
burp-startburp = ""
udiskie = ""
nemo = ""
paperwork = ""
jetbrains-studio = ""
neomutt = ""
gcr-prompter = ""
fontforge = ""
molotov = ""
shopping = ""
nm-connection-editor = ""
qalculate-gtk = ""
telegramdesktop = ""
streamlink-twitch-gui = ""
"Gimp-2.10" = ""
wlfreerdp = "󰀄"
gsimplecalc = ""
krita = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
kicad = ""
"(?i)alacritty" = ""
remote-viewer = ""
vimiv = ""
"(?i)kitty" = ""
"dmenu-pass generator" = ""
element = ""
"FFPWA-01H2RKDZVRMHNK0MK61SQY4BYV" = ""
plexamp = ""
scli = ""
slack = ""
work = ""
taskwarrior-tui = ""
obsidian = ""
pavucontrol = ""
xplr = ""
libreoffice-impress = ""
dmenu-pass = ""
rapid-photo-downloader = ""
vlc = ""
whatsapp-desktop = ""
org-qutebrowser-qutebrowser = ""
firefox = ""
darktable = ""
bleachbit = ""
".*transmission.*" = ""
org-telegram-desktop = ""
wireshark-gtk = ""
steam = ""
mpv = ""
songrec = ""
discord = ""
kak = ""
Signal = ""
spotify = ""
duolingo = ""
wayvnc = "󰀄"
"(?i)waydroid.*" = "droid"
chromium = ""
sun-awt-x11-xframepeer = ""
libreoffice-calc = ""
snappergui = ""
qutepreview = ""
cssh = ""
wire = "󰁀"
libreoffice-writer = ""
dmenu-clipboard = ""
dmenu-emoji = ""

[class_active]
"(?i)firefox" = "<span foreground='orange'> </span>"

[initial_class]

[title_in_class_active]

[title_in_initial_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]

[format]
dedup = true
dedup_inactive_fullscreen = true
delim = " "
workspace = "{id}:<span color='#ebdbb2'>{delim}{clients}</span>"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "<span color='#b8bb26'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"
