version: v0.5.0

general:
  default_ui:
    prefix: "   "
    suffix: " "
  focus_ui:
    prefix: "▸[ "
    suffix: " ]"
    style:
      fg: Cyan
  selection_ui:
    prefix: " { "
    suffix: " }"

node_types:
  directory:
    meta:
      icon: " "
    style:
      fg: Blue
  file:
    meta:
      icon: " "
    style:
      add_modifier:
        bits: 2
  symlink:
    meta:
      icon: " "

modes:
  builtin:
    default:
      key_bindings:
        on_key:
          e:
            help: editor
            messages:
              - BashExec: '${EDITOR:-vi} "${XPLR_FOCUS_PATH:?}"'
