version: v0.8.4

general:
  focus_ui:
    style:
      fg: Cyan

node_types:
  directory:
    meta:
      icon: ""
    style:
      fg: Blue
  file:
    meta:
      icon: ""
    style:
      add_modifiers: [Dim]
  symlink:
    meta:
      icon: ""
    style:
      sub_modifiers: [Italic]

modes:
  builtin:
    default:
      key_bindings:
        on_key:
          e:
            help: editor
            messages:
              - BashExec: '${EDITOR:-vi} "${XPLR_FOCUS_PATH:?}"'
          D:
            help: disk usage
            messages:
              - BashExec: ncdu
              - ClearScreen

    search:
      key_bindings:
        remaps:
          tab: right
