# capturer = "wlroots"
# capturer = "none" # Does not capture screen contents, just uses ALS to predict ideal screen brightness

# [als.iio]
# path = "/sys/bus/iio/devices"
# thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

# [als.time]
# thresholds = { 0 = "night", 7 = "dark", 9 = "dim", 11 = "normal", 13 = "bright", 16 = "normal", 18 = "dark", 20 = "night" }

[als.webcam]
video = 0
thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

# [als.none]

# TODO multi-monitor setup is not supported, but wanted!
[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wlroots"

[[keyboard]]
name = "laptop-keyboard"
path = "/sys/bus/platform/devices/dell-laptop/leds/dell::kbd_backlight"

# [[keyboard]]
# path = "/sys/bus/platform/devices/thinkpad_acpi/leds/tpacpi::kbd_backlight"

# Home
[[output.ddcutil]]
name = "D8VXF9CJ0EPB"
capturer = "wlroots"

# Work
[[output.ddcutil]]
name = "HH77Y71IC5YS"
capturer = "wlroots"

[[output.ddcutil]]
name = "9KFDW67326GB"
capturer = "wlroots"
