# External plugins
source "~/.config/kak/auto-pairs/rc/auto-pairs.kak"
source "~/.config/kak/vertical-selection/vertical-selection.kak"
source "~/.config/kak/langmap.kak/rc/langmap.kak"
source "~/.config/kak/restclient.kak/restclient.kak"
source "~/.config/kak/sudo-write.kak/sudo-write.kak"

# My configs
source "~/.config/kak/coding.kak"
source "~/.config/kak/files.kak"
source "~/.config/kak/mappings.kak"
source "~/.config/kak/ui.kak"
source "~/.config/kak/asterisk.kak"
