#!/bin/sh
selection="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection"
croc="kitty --hold --title 'Croc Send' croc send "

if [ -s "$selection" ]; then
    tar -cvf - -T "$selection" | $croc -
elif [ -e "$1" ]; then
    $croc "$1"
fi
