#!/bin/sh

selection="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection"
cast="kitty @ new-window --no-response --window-type os --cwd $PWD repeat 10 mkchromecast --encoder-backend ffmpeg -c aac --video --notifications -s -i "

if [ -s "$selection" ]; then
    xargs -0 -a "$selection" $cast
elif [ -e "$1" ]; then
    $cast "$1"
fi
