#!/bin/bash

selection="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection"
import="paperwork-shell -q -b import"

[ -f ~/Vault/.lock ] || echo "Please open-vault." && exit 1
if [ -s "$selection" ]; then
    xargs -0 -a "$selection" $import 2>/dev/null
elif [ -e "$1" ]; then
    $import "$1" 2>/dev/null
fi

read -p "Enter to exit."
