#!/bin/bash

selection="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection"
import="kitty @ new-window --no-response --window-type os --cwd $PWD paperwork-shell -b import "

[ -f ~/Vault/.lock ] || (echo "Please open-vault." && exit 1)
if [ -s "$selection" ]; then
    xargs -0 -a "$selection" $import
elif [ -e "$1" ]; then
    $import "$1"
fi

read -p "Enter to exit."
