#!/bin/bash

ESSID=$(nmcli -t -f active,ssid dev wifi| grep -e '^yes' | cut -d':' -f2 | tr '[:upper:]' '[:lower:]')
INTERFACE="$1"
STATUS=$2

case $STATUS in
  up)
    if [[ ${ESSID:0:4} != "truc" && ${ESSID:0:3} != "Air"
          && ${ESSID:0:4} != "phon"
          && ${INTERFACE:0:3} != "tun"
          && ${INTERFACE} != 'ens8u1u4' ]]; then
         # mullvad connect
         # nmcli con up WARP
         nmcli con up MyNAS
    else
        # mullvad disconnect
        # nmcli con down WARP
    fi
    systemctl restart systemd-resolved.service
    ;;
  down)
    ;;
  vpn-up)
    systemctl restart systemd-resolved.service
    ;;
  vpn-down)
    ;;
esac
