#!/bin/bash

VPN_NAME="France"
ESSID=$(iwgetid -r | tr '[:upper:]' '[:lower:]')

INTERFACE="$1"
STATUS=$2

case $STATUS in
  up)
    if [[ ${INTERFACE:0:3} != "tun" && ${INTERFACE:0:3} != "tap"
          && ${INTERFACE:0:2} != "vm" && ${INTERFACE:0:6} != "docker"
          && ${INTERFACE:0:11} != "enp59s0u1u2" && ${INTERFACE:0:5} != "virbr"
          && ${INTERFACE:0:5} != "vmnet" && ${INTERFACE:0:14} != "wg0"
          && ${INTERFACE:0:14} != "wwp0s20f0u2i12"
          && ${ESSID:0:4} != "truc" && ${ESSID:0:6} != "mobile"
          && ${ESSID:0:6} != "phonux" ]]; then
      nmcli con up "$VPN_NAME" 2>/dev/null
    fi
    systemctl restart kresd@1.service
    systemctl restart systemd-resolved.service
    py3-cmd refresh "whatismyip" "networkmanager" "weather_owm paris"
    ;;
  down)
    if nmcli con show --active | grep "$VPN_NAME"; then
      nmcli con down "$VPN_NAME" 2>/dev/null
    fi
    systemctl restart kresd@1.service
    systemctl restart systemd-resolved.service
    py3-cmd refresh "whatismyip" "networkmanager"
    ;;
  vpn-up)
    if [[ $INTERFACE == "tun-pia" ]]; then
      nmcli con down tun-pia-hard 2>/dev/null
      sysctl -w net.ipv6.conf.all.disable_ipv6=1
    fi
    systemctl restart kresd@1.service
    systemctl restart systemd-resolved.service
    py3-cmd refresh "whatismyip" "networkmanager"
    ;;
  vpn-down)
    if [[ $INTERFACE == "tun-pia" ]]; then
      sysctl -w net.ipv6.conf.all.disable_ipv6=0
    fi
    systemctl restart kresd@1.service
    systemctl restart systemd-resolved.service
    py3-cmd refresh "whatismyip" "networkmanager"
    ;;
esac
py3-cmd refresh "external_script nmtrust" "networkmanager" "frame wwan_frame"
