alias k='kubectl'
alias kc='kubectx "$(kubectx | fzy)"'
alias kd='k describe'
alias kgp!='kubectl get pod --all-namespaces'	alias kd!='kd --all-namespaces'
alias ke='k exec -ti'
alias kg='k get'
alias kg!='kg --all-namespaces'
alias kgp='kg pod'
alias kdel='k delete'
alias kgp!='kgp --all-namespaces'
alias kl='kubectl logs -f'
