program_options:
  tray: false
  automount: true
  notify: true
  notify_command: "notify-send --icon=drive-removable-media {{event}} {{device_presentation}}"
  password_prompt: ["pass", "personal/crypt/usb/{id_uuid}"]

device_config:
  - device_file: /dev/mmcblk0
    automount: false
