name: Dotfiles CI
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  test-repository:
    name: Test AUR repository
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - id: test
        name: Run pacman -Sy cyrinux test
        run: |
          make test

      - id: ping
        name: Ping healthchecks.io
        uses: indiesdev/curl@v1
        if: success()
        with:
          url: https://hc-ping.com/${{ secrets.curl_healthchecks_io }}
